version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"

  backend:
    build:
      context: ./backend 
      dockerfile: Dockerfile
    environment:
      - DATABASE_HOST=cloud-db.cpseqi6mmsuu.us-east-1.rds.amazonaws.com
      - DATABASE_USER=root
      - DATABASE_PASSWORD=Nourssine02
      - DATABASE_NAME=cloud
    ports:
      - "5001:5000"
    volumes:
      - ./backend/certs:/var/www/myapp/backend/certs
